# Generated by Django 4.2.7 on 2024-03-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='couleur',
            field=models.CharField(max_length=30),
        ),
    ]
