# Generated by Django 4.2.7 on 2024-03-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_categorie_itemimage_blogpost_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='couleur',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
